services:

    sqlserver:
        image: mcr.microsoft.com/azure-sql-edge:latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: ""
        ports:
            - "1433:1433"